### ISSUE TITLE
Linking Legacy Accounts

### ISSUE THREAD

**Issue by bryanveloso** [garbear/facebook-mediawiki#1]
I didn't find any reference to it in the documentation. Are users asked if they have an existing account with a wiki during this process? And can they link it?

**Comment by garbear** [comment]
Linking accounts might not work correctly in the current version. In the next version, the code has been refactored to take care of this and a few more edge cases. I'm currently testing compatibility with MW 1.18. I'll keep you posted.

Regards,
Garrett

**Comment by garbear** [comment]
The extension is now compatible with MW 1.17+. Account linking is supported in the newest development version (master branch). If you get a chance, please give the new version a try and create a ticket for any issues you find.

Regards,
Garrett

**Comment by bryanveloso** [comment]
Will do! Many thanks for such a quick turnaround!
