### ISSUE TITLE
Add support for Foreground skin

### ISSUE THREAD

**Issue by jthingelstad** [garbear/facebook-mediawiki#10]
@nischayn22 reported thingles/WikiApiary#118 requesting Foreground add support for the Facebook extension. It is not clear this is a Foreground issue or possibly this extension is dependent on Vector and won't work with other skins.

**Comment by garbear** [comment]
Hi thingles,

I read the other issue and feel the same way you do. If nischayn22 wants our code to play nicely together, he can investigate the issue and send us bugs to review.

**Comment by nischayn22** [comment]
Of course I can, and I might do that too when I get time. The issue was supposed to be a placeholder to let people know that the problem exists, not asking anyone for fixing.

**Comment by garbear** [comment]
OK, I closed it because the only "people" that have ever worked on this project are me :) Feel free to re-open as a PR if you get time to fix this
