### ISSUE TITLE
Request git

### ISSUE THREAD

**Issue by paladox** [garbear/facebook-mediawiki#11]
Hi please could you make a request http://www.mediawiki.org/wiki/Git/New_repositories/Requests to add this extension to git. I carnt make the request because I am not the author or developer.

**Comment by garbear** [comment]
This extension was in a mediawiki repo for a while, and ultimately removed because it was redundant and all development took place on github. It won't be re-added, and if I ever pick up development again (or another maintainer steps up) that'll happen here on github.

**Comment by paladox** [comment]
Ok.
