### ISSUE TITLE
Does not work under chrome or safari, only under firefox

### ISSUE THREAD

**Issue by jnozsc** [garbear/facebook-mediawiki#6]
Hi, garbear,

Thanks for your great work.

Recently, I want to user your extension in mywebsite, but after testing, I find it works only under firefox. When I test it under chrome, after login in with Facebook, the facebook account is already login in facebook's website, but in mediawiki website, the session/cookies can not be set correctly, as a result, the login page just keep loading.

Could you provide any hint to this problem? 

This is my mediawiki environment. 

```
Installed software

Product Version
MediaWiki   1.20.6 (ddc3327)
PHP 5.4.9-4ubuntu2.2 (apache2handler)
MySQL   5.5.31-log
Entry point URLs

Entry point URL
Article path    /$1
Script path [ ]
index.php   /index.php
api.php /api.php
load.php    /load.php

```

**Comment by garbear** [comment]
Thanks for the report. I don't have a test webserver set up at the moment, so I'm not sure when I'll be able to look into this. If you'd like to do some digging yourself, [SpecialConnect.php](https://github.com/garbear/facebook-mediawiki/blob/master/Facebook/SpecialConnect.php) is where the cookies should be set during the login process. (I try to keep super verbose comments, but feel free to ask for any clarifications.)

**Comment by jnozsc** [comment]
Hi Garbear,

Thanks for replying!

Well, if you don't mind, let me use a long paragraph to explain how I debug this extension and what error I get finally.

First of all, I just use

```
git clone https://github.com/garbear/facebook-mediawiki
```

to get latest source code of this extension. I did not specify any branch, so it should be at <b>master</b> branch.

I installed it in my Mediawiki server by following the instruction from the Mediawiki extension page.

<b>It doesn't work.</b>

I check apache error.log. Find <b>missing Class 'ExternalUser'</b>.

So I Google this class, find a 'ExternalUser.php' from wikia's folk repo of this extension.

And then, I placed this 'ExternalUser.php' to the folder of this extension and added 

``` php
include 'ExternalUser.php';
```

to FacebookUser.php.

It works well.

<b>BUT ONLY ON FIREFOX</b>

When I tested it on Google Chrome, after I typed my Facebook's username and password in the pop-up window, clicked  the 'login' button. When I refreshed the Facebook website, it already showed as 'already login' status.But, in my mediawiki website, the page kept automatically refreshing in the login page, and can not redirect to 'already login' status and page.

So, I guess maybe something wrong with the session/ cookies setting in Chrome, I check my Chrome setting, everything is default. I uninstall Chome and re-install it , still have the same issue.

Well, my next step is (has to be) debug this extension. After spending a whole 2 days debugging this extension. I assume I find the exact code which is related with this issue.

In <b>FacebookInit.php</b> line 46

``` php
$facebook = new FacebookAPI();
```

For debug, let's modify it to 

``` php
$facebook = new FacebookAPI();
error_log("==log===> ".$facebook->getUser(),0);
```

The additional statement will write variable <b>$facebook->getUser()</b> to apache error.log

When I try this on Firefox, it will return a positive integer, as 4 for Mark Mark Zuckerberg, 12345678 for some other people.
But when I try this on Chrome, it will always return <b>0</b>

So, my next step is: Search facebook->getUser() return zero at stackoverflow.

I try all of those solution, neither of them works.

I also tried to update the Facebook PHP SDK ( https://github.com/facebook/facebook-php-sdk )in this extension to latest version (v 3.2.2). Does not work.

I tested the example in Facebook PHP SDK, worked well on both Firefox and Chrome.

So I think maybe this issue is related with this line

``` php
$facebook = new FacebookAPI();
```

Actually, this line just call the construct function in FacebookAPI.php

So let's look through FacebookAPI.php

``` php
class FacebookAPI extends Facebook {
    // Constructor
    public function __construct() {
        global $wgFbAppId, $wgFbSecret;
        // Check to make sure config.default.php was renamed properly, unless we
        // are running update.php from the command line
        // TODO: use $wgCommandLineMode, if it is propper to do so
        if ( !defined( 'MW_CMDLINE_CALLBACK' ) && !self::isConfigSetup() ) {
            die ( '<strong>Please update $wgFbAppId and $wgFbSecret.</strong>' );
        }
        $config = array(
            'appId'      => $wgFbAppId,
            'secret'     => $wgFbSecret,
            'fileUpload' => false, // optional
        );
        parent::__construct( $config );
    }
// other codes
}}
```

only focus on these lines

``` php
        $config = array(
            'appId'      => $wgFbAppId,
            'secret'     => $wgFbSecret,
            'fileUpload' => false, // optional
        );
        parent::__construct( $config );
```

appId, already provided.
secret, already provide.
fileUpload, optional, does not matter.

so I guess maybe the problem is 

``` php
 parent::__construct( $config );
```

Well, this is the final status I got last week. This week I have to start working on other stuff, so I don't think I have enough time to look through this problem.

But, garbear, if you can pay at least a little attention on this issue, it will be my pleasure.

Because currently, as I know, there is no a website using a workable version of this extension except wikia. But wikia's version is too customized to re-use. I know, compared with your other famous project, this small project should not require your time, but I already spend a lot of time on it, but I fail, you maybe the wonder guy that can fix it.

I will give a help when you need test or more debug information on this extension and I really hope we can work together to make this extension reborn.

Best,
John

**Comment by jnozsc** [comment]
any update?

**Comment by garbear** [comment]
no, sorry - I haven't had time to look into this. Thank you for the detailed debug description - it will be quite helpful when I hunt down this issue.

**Comment by rakeshkumar125** [comment]
I have facing the same problem then i read out diffrerent forum & blogs then find the certain code but they are not working. The code make modification in function 

   protected function getCode() { on line number 577

<code>
  if (isset($_REQUEST['code'])) {
</code>
replace with 

<code>
$server_info = array_merge($_GET, $_POST, $_COOKIE);
        if (isset($server_info['code'])) {
</code>

In base_facebook.php file, find the makeRequest() method and check for following Line.
<code>
$opts = self::$CURL_OPTS; 
</code>
Immediately following it, add this line
<code>
$opts[CURLOPT_SSL_VERIFYPEER] = false;  
<code>

http://stackoverflow.com/questions/21367924/facebook-getuser-returning-0

But these solution not working i use caching in the opencart may issue came with this. 

So if you have an idea share it

**Comment by garbear** [comment]
sorry, jnozsc was able to uncover a lot of information on this issue but I don't see where you could dig a little further.

Facebook was 4 years old when I started this extensions. Now they're 10. Perhaps their php sdk relied on a feature that webkit has dropped since then (probably in the interest of security). Things like this happen when an API has been abandoned for years.

my code abstracts the API (although somewhat thinly), so the faulty facebook SDK can be swapped out for a newer PHP library with very little change to the code. possibly the only file you'd need to change is [FacebookAPI.php](https://github.com/garbear/facebook-mediawiki/blob/master/Facebook/FacebookAPI.php). that's where I suggest you start.
